# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Go-Player
version:      0.07
version_from: lib/Games/Go/Player.pm
installdirs:  site
requires:
    Carp:                          0
    DB_File:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
